[package]
name = "deadbeef-rust-plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
const-str = "0.5.3"
pipewire = "0.5.0"

[build-dependencies]
bindgen = "0.63.0"
