[package]
name = "deadbeef-sys"
version = "0.1.0"
rust-version = "1.64"
edition = "2021"

[dependencies]
lossycstring = {path = "../lossycstring"}
thiserror = "1"
once_cell = "1.18.0"

[build-dependencies]
bindgen = {version = "0.59.0"}
